<?php

namespace Database\Seeders;

use App\Models\Invoice;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class InvoiceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $invoices = [
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-001',
                'supplier_name' => 'Tech Solutions Ltd',
                'supplier_tax_id' => '12345678',
                'net_amount' => 1000.00,
                'vat_amount' => 200.00,
                'gross_amount' => 1200.00,
                'currency' => 'UAH',
                'status' => 'pending',
                'issue_date' => '2026-08-01',
                'due_date' => '2026-08-31',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-002',
                'supplier_name' => 'Global Logistics Inc',
                'supplier_tax_id' => '87654321',
                'net_amount' => 500.00,
                'vat_amount' => 100.00,
                'gross_amount' => 600.00,
                'currency' => 'UAH',
                'status' => 'approved',
                'issue_date' => '2026-08-10',
                'due_date' => '2026-09-10',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-003',
                'supplier_name' => 'Office Supplies Co',
                'supplier_tax_id' => '55667788',
                'net_amount' => 250.00,
                'vat_amount' => 50.00,
                'gross_amount' => 300.00,
                'currency' => 'UAH',
                'status' => 'rejected',
                'issue_date' => '2026-08-15',
                'due_date' => null,
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-004',
                'supplier_name' => 'Digital Systems Ukraine',
                'supplier_tax_id' => '34125678',
                'net_amount' => 1750.00,
                'vat_amount' => 350.00,
                'gross_amount' => 2100.00,
                'currency' => 'UAH',
                'status' => 'pending',
                'issue_date' => '2026-07-20',
                'due_date' => '2026-08-20',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-005',
                'supplier_name' => 'West Trade Group',
                'supplier_tax_id' => '98234567',
                'net_amount' => 820.00,
                'vat_amount' => 164.00,
                'gross_amount' => 984.00,
                'currency' => 'UAH',
                'status' => 'pending',
                'issue_date' => '2026-08-18',
                'due_date' => '2026-09-18',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-006',
                'supplier_name' => 'Modern Equipment LLC',
                'supplier_tax_id' => '44781236',
                'net_amount' => 3200.00,
                'vat_amount' => 640.00,
                'gross_amount' => 3840.00,
                'currency' => 'UAH',
                'status' => 'approved',
                'issue_date' => '2026-08-05',
                'due_date' => '2026-09-05',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-007',
                'supplier_name' => 'Clean Office Services',
                'supplier_tax_id' => '67123489',
                'net_amount' => 450.00,
                'vat_amount' => 90.00,
                'gross_amount' => 540.00,
                'currency' => 'UAH',
                'status' => 'pending',
                'issue_date' => '2026-07-28',
                'due_date' => '2026-08-12',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-008',
                'supplier_name' => 'Nova Marketing Agency',
                'supplier_tax_id' => '52987631',
                'net_amount' => 1250.00,
                'vat_amount' => 250.00,
                'gross_amount' => 1500.00,
                'currency' => 'UAH',
                'status' => 'pending',
                'issue_date' => '2026-08-21',
                'due_date' => '2026-09-21',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-009',
                'supplier_name' => 'Eastern Transport Ltd',
                'supplier_tax_id' => '76345129',
                'net_amount' => 2100.00,
                'vat_amount' => 420.00,
                'gross_amount' => 2520.00,
                'currency' => 'UAH',
                'status' => 'approved',
                'issue_date' => '2026-08-07',
                'due_date' => '2026-09-07',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-010',
                'supplier_name' => 'Smart IT Solutions',
                'supplier_tax_id' => '31876542',
                'net_amount' => 980.00,
                'vat_amount' => 196.00,
                'gross_amount' => 1176.00,
                'currency' => 'UAH',
                'status' => 'rejected',
                'issue_date' => '2026-08-09',
                'due_date' => null,
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-011',
                'supplier_name' => 'ProBuild Materials',
                'supplier_tax_id' => '49561237',
                'net_amount' => 4600.00,
                'vat_amount' => 920.00,
                'gross_amount' => 5520.00,
                'currency' => 'UAH',
                'status' => 'pending',
                'issue_date' => '2026-08-11',
                'due_date' => '2026-09-11',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-012',
                'supplier_name' => 'City Print Studio',
                'supplier_tax_id' => '83214567',
                'net_amount' => 360.00,
                'vat_amount' => 72.00,
                'gross_amount' => 432.00,
                'currency' => 'UAH',
                'status' => 'pending',
                'issue_date' => '2026-07-15',
                'due_date' => '2026-08-01',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-013',
                'supplier_name' => 'Cloud Services Europe',
                'supplier_tax_id' => '76439821',
                'net_amount' => 2750.00,
                'vat_amount' => 550.00,
                'gross_amount' => 3300.00,
                'currency' => 'UAH',
                'status' => 'approved',
                'issue_date' => '2026-08-12',
                'due_date' => '2026-09-12',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-014',
                'supplier_name' => 'Fresh Food Distribution',
                'supplier_tax_id' => '61827345',
                'net_amount' => 1340.00,
                'vat_amount' => 268.00,
                'gross_amount' => 1608.00,
                'currency' => 'UAH',
                'status' => 'pending',
                'issue_date' => '2026-08-14',
                'due_date' => '2026-09-14',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-015',
                'supplier_name' => 'Security Systems UA',
                'supplier_tax_id' => '38762145',
                'net_amount' => 1900.00,
                'vat_amount' => 380.00,
                'gross_amount' => 2280.00,
                'currency' => 'UAH',
                'status' => 'rejected',
                'issue_date' => '2026-08-16',
                'due_date' => null,
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-016',
                'supplier_name' => 'Business Consulting Group',
                'supplier_tax_id' => '71263849',
                'net_amount' => 2250.00,
                'vat_amount' => 450.00,
                'gross_amount' => 2700.00,
                'currency' => 'UAH',
                'status' => 'approved',
                'issue_date' => '2026-08-17',
                'due_date' => '2026-09-17',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-017',
                'supplier_name' => 'Ukrainian Telecom Services',
                'supplier_tax_id' => '45678123',
                'net_amount' => 690.00,
                'vat_amount' => 138.00,
                'gross_amount' => 828.00,
                'currency' => 'UAH',
                'status' => 'pending',
                'issue_date' => '2026-07-25',
                'due_date' => '2026-08-10',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-018',
                'supplier_name' => 'Industrial Parts Ltd',
                'supplier_tax_id' => '92561438',
                'net_amount' => 3850.00,
                'vat_amount' => 770.00,
                'gross_amount' => 4620.00,
                'currency' => 'UAH',
                'status' => 'pending',
                'issue_date' => '2026-08-19',
                'due_date' => '2026-09-19',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-019',
                'supplier_name' => 'Green Energy Solutions',
                'supplier_tax_id' => '53147829',
                'net_amount' => 5100.00,
                'vat_amount' => 1020.00,
                'gross_amount' => 6120.00,
                'currency' => 'UAH',
                'status' => 'approved',
                'issue_date' => '2026-08-20',
                'due_date' => '2026-09-20',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-020',
                'supplier_name' => 'Express Delivery Ukraine',
                'supplier_tax_id' => '67432158',
                'net_amount' => 740.00,
                'vat_amount' => 148.00,
                'gross_amount' => 888.00,
                'currency' => 'UAH',
                'status' => 'pending',
                'issue_date' => '2026-08-22',
                'due_date' => '2026-09-22',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-021',
                'supplier_name' => 'Retail Partners LLC',
                'supplier_tax_id' => '81926347',
                'net_amount' => 1560.00,
                'vat_amount' => 312.00,
                'gross_amount' => 1872.00,
                'currency' => 'UAH',
                'status' => 'pending',
                'issue_date' => '2026-07-30',
                'due_date' => '2026-08-15',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-022',
                'supplier_name' => 'Data Analytics Pro',
                'supplier_tax_id' => '36251478',
                'net_amount' => 2900.00,
                'vat_amount' => 580.00,
                'gross_amount' => 3480.00,
                'currency' => 'UAH',
                'status' => 'approved',
                'issue_date' => '2026-08-23',
                'due_date' => '2026-09-23',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-023',
                'supplier_name' => 'Kyiv Equipment Supply',
                'supplier_tax_id' => '74561283',
                'net_amount' => 1180.00,
                'vat_amount' => 236.00,
                'gross_amount' => 1416.00,
                'currency' => 'UAH',
                'status' => 'rejected',
                'issue_date' => '2026-08-24',
                'due_date' => null,
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-024',
                'supplier_name' => 'Professional Services Group',
                'supplier_tax_id' => '58321476',
                'net_amount' => 3400.00,
                'vat_amount' => 680.00,
                'gross_amount' => 4080.00,
                'currency' => 'UAH',
                'status' => 'pending',
                'issue_date' => '2026-08-25',
                'due_date' => '2026-09-25',
            ],
            [
                'id' => (string) Str::uuid(),
                'number' => 'INV-2026-025',
                'supplier_name' => 'Future Technologies LLC',
                'supplier_tax_id' => '69743125',
                'net_amount' => 4200.00,
                'vat_amount' => 840.00,
                'gross_amount' => 5040.00,
                'currency' => 'UAH',
                'status' => 'approved',
                'issue_date' => '2026-08-26',
                'due_date' => '2026-09-26',
            ],
        ];

        foreach ($invoices as $data) {
            Invoice::updateOrCreate(['number' => $data['number']], $data);
        }
    }
}
